# Site Settings
title                    : "Renchao Li (李仁超)"
description              : "PhD candidate in HIT"
url                      : "https://lirc0618.github.io"
repository               : "lirc0618/lirc0618.github.io"

# google analytics
# google_analytics_id      : G-SWFCX99KQZ

# SEO Related
# google_site_verification : b_BbOIt7d513ZXYDw-YRMicO6O5tthYiouqWDdWjGTU
# bing_site_verification   : B5AA590E7B9C03956A6F7DEC0F776211
# baidu_site_verification  : code-ZxFK3f4pfb

# Site Author
author:
  name             : "Renchao Li (李仁超)"
  avatar           : "images/wechat_avatar_1024x1024.jpg"
  bio              : "Research focus on Hardware Security, Physical Unclonable Function (PUF), Printed Electronics and AI Authentication."
  location         : "Shenzhen"
  email            : "lirc@stu.hit.edu.cn"
  github           : "lirc0618"
  orcid            : "https://orcid.org/0009-0008-7293-2583"

# Reading Files
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - README.md
  - assets/js/_main.js
  - run_server.sh
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-redirect-from
